/**
 * Автопроверка для агента/CI: build, форматы упражнений, lint, prod smoke.
 * node scripts/agent-qa.mjs [--skip-prod] [--skip-prod-roles] [--skip-lint]
 */
import { spawnSync } from 'node:child_process'
import { existsSync } from 'node:fs'

const ORIGIN = process.env.QA_ORIGIN ?? 'https://fitness-diary-bice.vercel.app'
const skipProd = process.argv.includes('--skip-prod')
const skipProdRoles = process.argv.includes('--skip-prod-roles')
const skipLint = process.argv.includes('--skip-lint')

let failed = 0

function run(label, cmd, args, opts = {}) {
  console.log(`\n▶ ${label}`)
  const r = spawnSync(cmd, args, { stdio: 'inherit', shell: true, ...opts })
  if (r.status !== 0) {
    console.error(`✗ ${label}`)
    failed++
  } else {
    console.log(`✓ ${label}`)
  }
}

function check(cond, label) {
  if (cond) {
    console.log(`✓ ${label}`)
  } else {
    console.error(`✗ ${label}`)
    failed++
  }
}

run('build', 'npm', ['run', 'build'])
run('product brand', 'node', ['scripts/verify-product-brand.mjs'])
run('exercise formats', 'node', ['scripts/verify-exercise-format.mjs'])
run('training set laterality', 'node', ['scripts/verify-training-set-laterality.mjs'])
run('training persist status', 'node', ['scripts/verify-training-persist-status.mjs'])
run('training membership debit', 'node', ['scripts/verify-training-membership-debit.mjs'])
run('sync offline-first', 'node', ['scripts/verify-sync-offline.mjs'])
run('security L1 audit', 'node', ['scripts/verify-security-l1-audit.mjs'])
run('critical hall', 'node', ['scripts/verify-critical-hall.mjs'])
run('network reachability', 'node', ['scripts/verify-network-reachability.mjs'])
run('app stability', 'node', ['scripts/verify-app-stability.mjs'])
run('auth sign-in fallback', 'node', ['scripts/verify-auth-sign-in-fallback.mjs'])
run('auth sign-in fast path', 'node', ['scripts/verify-auth-sign-in-fast-path.mjs'])
run('auth login resolve', 'node', ['scripts/verify-auth-login-resolve.mjs'])
run('pg migrate order', 'node', ['scripts/verify-pg-migrate-order.mjs'])
run('portable host health', 'node', ['scripts/verify-portable-host.mjs'])
run('user identity cache', 'node', ['scripts/verify-user-identity-cache.mjs'])
run('sync unsynced re-queue', 'node', ['scripts/verify-sync-unsynced.mjs'])
run('client trainings prune', 'node', ['scripts/verify-client-trainings-prune.mjs'])
run('bulk exercises parser', 'node', ['scripts/verify-bulk-exercises.mjs'])
run('client birthdays', 'node', ['scripts/verify-client-birthdays.mjs'])
run('membership type stats', 'node', ['scripts/verify-membership-type-stats.mjs'])
run('training membership link', 'node', ['scripts/verify-training-membership-link.mjs'])
run('membership types pull', 'node', ['scripts/verify-membership-types-pull.mjs'])
run('membership types merge', 'node', ['scripts/verify-membership-types-merge.mjs'])
run('membership type code rename', 'node', ['scripts/verify-membership-type-code.mjs'])
run('sales membership types access', 'node', ['scripts/verify-sales-membership-types-access.mjs'])
run('sales bundle profile', 'node', ['scripts/verify-sales-bundle-profile.mjs'])
run('price list core', 'node', ['scripts/verify-price-list.mjs'])
run('membership push payload', 'node', ['scripts/verify-membership-push-payload.mjs'])
run('membership used reconcile', 'node', ['scripts/verify-membership-used-reconcile.mjs'])
run('membership total guard', 'node', ['scripts/verify-membership-total-guard.mjs'])
run('membership delete confirm', 'node', ['scripts/verify-membership-delete.mjs'])
run('membership early/late activate', 'node', ['scripts/verify-membership-early-activate.mjs'])
run('date ru calendar month', 'node', ['scripts/verify-date-ru.mjs'])
run('club client period', 'node', ['scripts/verify-club-client-period.mjs'])
run('club stats hall', 'node', ['scripts/verify-club-stats-hall.mjs'])
run('admin clients archive browse', 'node', ['scripts/verify-admin-clients-archive.mjs'])
run('admin clients list href', 'node', ['scripts/verify-admin-clients-list-href.mjs'])
run('admin clients cross-hall search', 'node', ['scripts/verify-admin-clients-cross-hall-search.mjs'])
run('client workspace scope', 'node', ['scripts/verify-client-workspace-scope.mjs'])
run('admin clients keepalive', 'node', ['scripts/verify-admin-clients-keepalive.mjs'])
run('client card return', 'node', ['scripts/verify-client-card-return.mjs'])
run('breadcrumbs', 'node', ['scripts/verify-breadcrumbs.mjs'])
run('club monthly year', 'node', ['scripts/verify-club-monthly-year.mjs'])
run('club sales profit', 'node', ['scripts/verify-club-sales-profit.mjs'])
run('club finance forecast', 'node', ['scripts/verify-club-finance-forecast.mjs'])
run('club net profit margin', 'node', ['scripts/verify-club-net-profit-margin.mjs'])
run('club finance purchase mix', 'node', ['scripts/verify-club-finance-purchase-mix.mjs'])
run('sales strategy admin finance', 'node', ['scripts/verify-sales-strategy-admin-finance.mjs'])
run('sales strategy nk uk edit', 'node', ['scripts/verify-sales-strategy-nk-uk-edit.mjs'])
run('trainer payroll', 'node', ['scripts/verify-trainer-payroll.mjs'])
run('trainer day payroll forecast', 'node', ['scripts/verify-trainer-day-payroll-forecast.mjs'])
run('trainer month payroll forecast', 'node', ['scripts/verify-trainer-month-payroll-forecast.mjs'])
run('trainer pay tiers', 'node', ['scripts/verify-trainer-pay-tiers.mjs'])
run('trainer pay plan', 'node', ['scripts/verify-trainer-pay-plan.mjs'])
run('trainer pay profile', 'node', ['scripts/verify-trainer-pay-profile.mjs'])
run('trainer pay month snapshot', 'node', ['scripts/verify-trainer-pay-month-snapshot.mjs'])
run('trainer auth admin', 'node', ['scripts/verify-trainer-auth-admin.mjs'])
run('trainer tablet mode', 'node', ['scripts/verify-trainer-tablet-mode.mjs'])
run('filter staff by club', 'node', ['scripts/verify-filter-staff-by-club.mjs'])
run('aerobic payroll', 'node', ['scripts/verify-aerobic-payroll.mjs'])
run('sales plan progress', 'node', ['scripts/verify-sales-plan-progress.mjs'])
run('sales plan levels', 'node', ['scripts/verify-sales-plan-levels.mjs'])
run('supervisor expense parts', 'node', ['scripts/verify-supervisor-expense-parts.mjs'])
run('sales plan matrix compare', 'node', ['scripts/verify-sales-plan-matrix-compare.mjs'])
run('sales promotions', 'node', ['scripts/verify-sales-promotions.mjs'])
run('sales plan PZ DK suggest', 'node', ['scripts/verify-sales-plan-pz-dk-suggest.mjs'])
run('sales plan hall renewals', 'node', ['scripts/verify-sales-plan-hall-renewals.mjs'])
run('sales plan hall top-up', 'node', ['scripts/verify-sales-plan-hall-top-up.mjs'])
run('sales strategy playbook', 'node', ['scripts/verify-sales-strategy-playbook.mjs'])
run('sales strategy playbook hall lists', 'node', ['scripts/verify-sales-strategy-playbook-hall-lists.mjs'])
run('sales strategy archive drift', 'node', ['scripts/verify-sales-strategy-archive-drift.mjs'])
run('sales strategy snapshot', 'node', ['scripts/verify-sales-strategy-snapshot.mjs'])
run('sales plan row persist', 'node', ['scripts/verify-sales-plan-row-persist.mjs'])
run('sales plan dk edit warn', 'node', ['scripts/verify-sales-plan-dk-edit-warn.mjs'])
run('sales strategy package board', 'node', ['scripts/verify-sales-strategy-package-board.mjs'])
run('sales hall anchor', 'node', ['scripts/verify-sales-hall-anchor.mjs'])
run('tz price list', 'node', ['scripts/verify-tz-price-list.mjs'])
run('tz price list print', 'node', ['scripts/verify-tz-price-list-print.mjs'])
run('az price list', 'node', ['scripts/verify-az-price-list.mjs'])
run('az price list print', 'node', ['scripts/verify-az-price-list-print.mjs'])
run('sales manager stats', 'node', ['scripts/verify-sales-manager-stats.mjs'])
run('sales client segment', 'node', ['scripts/verify-sales-client-segment.mjs'])
run('sales payments import', 'node', ['scripts/verify-sales-payments-import.mjs'])
run('client card unique in club', 'node', ['scripts/verify-client-card-unique.mjs'])
run('sales payments link', 'node', ['scripts/verify-sales-payments-link.mjs'])
run('PZ trainings Excel import', 'node', ['scripts/verify-pz-trainings-report-import.mjs'])
run('desk closing import', 'node', ['scripts/verify-desk-closing-import.mjs'])
run('desk membership ledger', 'node', ['scripts/verify-desk-membership-ledger.mjs'])
run('desk az session deduct', 'node', ['scripts/verify-desk-az-session-deduct.mjs'])
run('desk hall clients tabs', 'node', ['scripts/verify-desk-hall-clients.mjs'])
run('desk manual client create', 'node', ['scripts/verify-desk-manual-client-create.mjs'])
run('membership hall multi', 'node', ['scripts/verify-membership-hall.mjs'])
run('client trainer reassign', 'node', ['scripts/verify-client-trainer-reassign.mjs'])
run('membership paid_amount field', 'node', ['scripts/verify-membership-paid-amount.mjs'])
run('desk client birth form', 'node', ['scripts/verify-desk-client-birth-form.mjs'])
run('desk client form merge', 'node', ['scripts/verify-desk-client-form-merge.mjs'])
run('deletion audit', 'node', ['scripts/verify-deletion-audit.mjs'])
run('client hard delete confirm', 'node', ['scripts/verify-client-hard-delete-confirm.mjs'])
run('client archive reason', 'node', ['scripts/verify-client-archive-reason.mjs'])
run('client archive expected return', 'node', ['scripts/verify-client-archive-expected-return.mjs'])
run('client hall lifecycle', 'node', ['scripts/verify-client-hall-lifecycle.mjs'])
run('club sms campaign', 'node', ['scripts/verify-club-sms-campaign.mjs'])
run('club sms campaign result', 'node', ['scripts/verify-club-sms-campaign-result.mjs'])
run('sale clips match holding', 'node', ['scripts/verify-sale-clips.mjs'])
run('pnk funnel stages', 'node', ['scripts/verify-pnk-stages.mjs'])
run('pnk funnel events', 'node', ['scripts/verify-pnk-funnel-events.mjs'])
run('pnk refuse scenario buttons', 'node', ['scripts/verify-pnk-refuse-scenario.mjs'])
run('pnk wizard steps', 'node', ['scripts/verify-pnk-wizard.mjs'])
run('pnk wizard nav hat', 'node', ['scripts/verify-pnk-wizard-nav.mjs'])
run('pnk visit quality', 'node', ['scripts/verify-pnk-visit-quality.mjs'])
run('pnk bz completed count', 'node', ['scripts/verify-pnk-bz-completed.mjs'])
run('pnk trial training start', 'node', ['scripts/verify-pnk-trial-training.mjs'])
run('pnk coach notify', 'node', ['scripts/verify-pnk-coach-notify.mjs'])
run('pnk client notify', 'node', ['scripts/verify-pnk-client-notify.mjs'])
run('pnk trainer glance', 'node', ['scripts/verify-pnk-trainer-glance.mjs'])
run('pnk manager board', 'node', ['scripts/verify-pnk-manager-board.mjs'])
run('pnk manager home glance', 'node', ['scripts/verify-pnk-manager-home-glance.mjs'])
run('pnk home glance revalidate', 'node', ['scripts/verify-pnk-home-glance-revalidate.mjs'])
run('sales manager role', 'node', ['scripts/verify-sales-manager-role.mjs'])
run('supervisor access', 'node', ['scripts/verify-supervisor-access.mjs'])
run('sales manager clients', 'node', ['scripts/verify-sales-manager-clients.mjs'])
run('sales draft storage', 'node', ['scripts/verify-admin-sales-draft.mjs'])
run('sales plan presence', 'node', ['scripts/verify-sales-plan-presence.mjs'])
run('club month analytics', 'node', ['scripts/verify-club-month-analytics.mjs'])
run('gemini analytics', 'node', ['scripts/verify-gemini-analytics.mjs'])
run('iskra neural tts', 'node', ['scripts/verify-iskra-tts.mjs'])
run('iskra quick chips', 'node', ['scripts/verify-iskra-quick-chips.mjs'])
run('iskra data availability', 'node', ['scripts/verify-iskra-data-availability.mjs'])
run('gemini trainer contour', 'node', ['scripts/verify-gemini-trainer-contour.mjs'])
run('iskra trainer routing', 'node', ['scripts/verify-iskra-trainer-routing.mjs'])
run('iskra advisor', 'node', ['scripts/verify-iskra-advisor.mjs'])
run('iskra response mode', 'node', ['scripts/verify-iskra-response-mode.mjs'])
run('iskra panel segment', 'node', ['scripts/verify-iskra-panel-segment.mjs'])
run('iskra panel contour', 'node', ['scripts/verify-iskra-panel-contour.mjs'])
run('iskra business playbooks', 'node', ['scripts/verify-iskra-business-playbooks.mjs'])
run('iskra knowledge base', 'node', ['scripts/verify-iskra-knowledge-base.mjs'])
run('iskra planerka feed', 'node', ['scripts/verify-iskra-planerka-feed.mjs'])
run('iskra curator contour', 'node', ['scripts/verify-iskra-curator-contour.mjs'])
run('iskra month memory', 'node', ['scripts/verify-iskra-month-memory.mjs'])
run('iskra learning', 'node', ['scripts/verify-iskra-learning.mjs'])
run('iskra advice outcome', 'node', ['scripts/verify-iskra-advice-outcome.mjs'])
run('iskra owner brief', 'node', ['scripts/verify-iskra-owner-brief.mjs'])
run('iskra inaction pack', 'node', ['scripts/verify-iskra-inaction.mjs'])
run('iskra north star', 'node', ['scripts/verify-iskra-north-star.mjs'])
run('iskra dispatch', 'node', ['scripts/verify-iskra-dispatch.mjs'])
run('iskra dispatch sender push', 'node', ['scripts/verify-iskra-dispatch-sender-push.mjs'])
run('iskra reply display', 'node', ['scripts/verify-iskra-reply-display.mjs'])
run('trainer push', 'node', ['scripts/verify-trainer-push.mjs'])
run('operations tasks', 'node', ['scripts/verify-operations-tasks.mjs'])
run('iskra proactive', 'node', ['scripts/verify-iskra-proactive.mjs'])
run('stats agg parity', 'node', ['scripts/verify-stats-agg-parity.mjs'])
run('challenge max reps', 'node', ['scripts/verify-challenge-max-reps.mjs'])
run('membership stats refresh', 'node', ['scripts/verify-membership-stats-refresh.mjs'])
run('training superset', 'node', ['scripts/verify-training-superset.mjs'])
run('training form step memory', 'node', ['scripts/verify-training-form-step-memory.mjs'])
run('training draft page epoch', 'node', ['scripts/verify-training-draft-page-epoch.mjs'])
run('training draft session cache', 'node', ['scripts/verify-training-draft-session-cache.mjs'])
run('last exercise result', 'node', ['scripts/verify-last-exercise-result.mjs'])
run('app diagnostics', 'node', ['scripts/verify-app-diagnostics.mjs'])
run('client weight push', 'node', ['scripts/verify-client-weight-push.mjs'])
run('app error journal', 'node', ['scripts/verify-app-error-journal.mjs'])
run('project health', 'node', ['scripts/verify-project-health.mjs'])
run('local db club query', 'node', ['scripts/verify-local-db-club-query.mjs'])
run('trainer pull incremental', 'node', ['scripts/verify-trainer-pull-incremental.mjs'])
run('trainer archive pull prune', 'node', ['scripts/verify-trainer-archive-pull-prune.mjs'])
run('trainer period stats remote', 'node', ['scripts/verify-trainer-period-stats-remote.mjs'])
run('enrich inactive clients local', 'node', ['scripts/verify-enrich-inactive-clients-local.mjs'])
run('club monthly years bounds', 'node', ['scripts/verify-club-monthly-years-bounds.mjs'])
run('idb retention', 'node', ['scripts/verify-idb-retention.mjs'])
run('draft trainings query', 'node', ['scripts/verify-draft-trainings-query.mjs'])
run('challenges club query', 'node', ['scripts/verify-challenges-club-query.mjs'])
run('client counts local', 'node', ['scripts/verify-client-counts-local.mjs'])
run('coach quality', 'node', ['scripts/verify-coach-quality.mjs'])
run('client retention', 'node', ['scripts/verify-client-retention.mjs'])
run('client restore event', 'node', ['scripts/verify-client-restore-event.mjs'])
run('home glance cache', 'node', ['scripts/verify-home-glance-cache.mjs'])
run('ble heart rate', 'node', ['scripts/verify-ble-heart-rate.mjs'])
run('hr session agg', 'node', ['scripts/verify-hr-session-agg.mjs'])
run('hr session persist', 'node', ['scripts/verify-hr-session-persist.mjs'])
run('hr after from live', 'node', ['scripts/verify-hr-after-from-live.mjs'])
run('loyalty', 'node', ['scripts/verify-loyalty.mjs'])
run('loyalty persist', 'node', ['scripts/verify-loyalty-persist.mjs'])
run('loyalty api', 'node', ['scripts/verify-loyalty-api.mjs'])
run('loyalty ui', 'node', ['scripts/verify-loyalty-ui.mjs'])
run('loyalty redeem', 'node', ['scripts/verify-loyalty-redeem.mjs'])
run('loyalty archive', 'node', ['scripts/verify-loyalty-archive.mjs'])
run('loyalty settings', 'node', ['scripts/verify-loyalty-settings.mjs'])
run('loyalty integration', 'node', ['scripts/verify-loyalty-integration.mjs'])
run('visual viewport chrome pin', 'node', ['scripts/verify-visual-viewport-chrome-pin.mjs'])
run('trainer attention summary', 'node', ['scripts/verify-trainer-attention-summary.mjs'])
run('trainer journal clients', 'node', ['scripts/verify-trainer-journal-clients.mjs'])
run('trainer journal filter', 'node', ['scripts/verify-trainer-journal-filter.mjs'])
run('client trainings prune truncated', 'node', ['scripts/verify-client-trainings-prune-truncated.mjs'])
run('client trainings ensure', 'node', ['scripts/verify-client-trainings-ensure.mjs'])
run('client list signals', 'node', ['scripts/verify-client-list-signals.mjs'])
run('client list membership type', 'node', ['scripts/verify-client-list-membership-type.mjs'])
run('trainer client outreach', 'node', ['scripts/verify-trainer-client-outreach.mjs'])
run('trainer outreach queue', 'node', ['scripts/verify-trainer-outreach-queue.mjs'])
run('moi zvonki club sms', 'node', ['scripts/verify-moi-zvonki.mjs'])
run('moi zvonki make call', 'node', ['scripts/verify-moi-zvonki-call.mjs'])
run('moi zvonki per-club config', 'node', ['scripts/verify-moi-zvonki-club-config.mjs'])
run('club desk max outreach', 'node', ['scripts/verify-club-client-max-outreach.mjs'])
run('club sms mode', 'node', ['scripts/verify-club-sms-mode.mjs'])
run('club sms templates', 'node', ['scripts/verify-club-sms-templates.mjs'])
run('club sms sent mark', 'node', ['scripts/verify-club-sms-sent-mark.mjs'])
run('club sms log', 'node', ['scripts/verify-club-sms-log.mjs'])
run('club call log', 'node', ['scripts/verify-club-call-log.mjs'])
run('club call outcome', 'node', ['scripts/verify-club-call-outcome.mjs'])
run('club call inbound', 'node', ['scripts/verify-club-call-inbound.mjs'])
run('club call recording ui', 'node', ['scripts/verify-club-call-recording-ui.mjs'])
run('club call sheet note chips', 'node', ['scripts/verify-club-call-sheet-note-chips.mjs'])
run('club call funnel chips', 'node', ['scripts/verify-club-call-funnel-chips.mjs'])
run('club call overlay scroll lock', 'node', ['scripts/verify-club-call-overlay-scroll-lock.mjs'])
run('client outreach history range', 'node', ['scripts/verify-client-outreach-history-range.mjs'])
run('sales call today', 'node', ['scripts/verify-sales-call-today.mjs'])
run('attention side placement', 'node', ['scripts/verify-attention-side-placement.mjs'])
run('attention presence session', 'node', ['scripts/verify-attention-presence-session.mjs'])
run('club outreach stats', 'node', ['scripts/verify-club-outreach-stats.mjs'])
run('client name format', 'node', ['scripts/verify-client-name-format.mjs'])
run('admin club day summary', 'node', ['scripts/verify-admin-club-day-summary.mjs'])
run('admin home attention', 'node', ['scripts/verify-admin-home-attention.mjs'])
run('admin client quick filters', 'node', ['scripts/verify-admin-client-quick-filters.mjs'])
run('trainer clients browse filters', 'node', ['scripts/verify-trainer-clients-browse-filters.mjs'])
run('admin clients az direction filter', 'node', ['scripts/verify-admin-clients-az-direction-filter.mjs'])
run('admin clients archive hall', 'node', ['scripts/verify-admin-clients-archive-hall.mjs'])
run('nutrition plan', 'node', ['scripts/verify-nutrition-plan.mjs'])
run('nutrition meal pairing', 'node', ['scripts/verify-nutrition-meal-pairing.mjs'])
run('nutrition referents', 'node', ['scripts/verify-nutrition-referents.mjs'])
run('nutrition plan history', 'node', ['scripts/verify-nutrition-plan-history.mjs'])
run('nutrition plan session', 'node', ['scripts/verify-nutrition-plan-session.mjs'])
run('nutrition prod flow', 'node', ['scripts/verify-nutrition-prod-flow.mjs'])
run('nutrition survey storage', 'node', ['scripts/verify-nutrition-survey-storage.mjs'])
run('client weight', 'node', ['scripts/verify-client-weight.mjs'])
run('weight import', 'node', ['scripts/verify-weight-import.mjs'])
run('BMI scale', 'node', ['scripts/verify-bmi-scale.mjs'])
run('health card', 'node', ['scripts/verify-health-card.mjs'])
run('nutrition products', 'node', ['scripts/verify-nutrition-products.mjs'])
run('homework plan', 'node', ['scripts/verify-homework-plan.mjs'])
run('sync outbound label', 'node', ['scripts/verify-sync-outbound-label.mjs'])
run('sync motivation', 'node', ['scripts/verify-sync-motivation.mjs'])
run('sync header pull', 'node', ['scripts/verify-sync-header-pull.mjs'])

if (!skipLint) {
  run('lint', 'npm', ['run', 'lint'])
}

if (!skipProd) {
  console.log('\n▶ prod smoke')
  try {
    const home = await fetch(`${ORIGIN}/`)
    check(home.status === 200, `GET / → ${home.status}`)

    const apiChecks = [
      ['GET trainer-pull', `${ORIGIN}/api/trainer-pull`, 'GET', 401],
      ['POST trainer-pull', `${ORIGIN}/api/trainer-pull`, 'POST', 405],
      ['GET list-trainers', `${ORIGIN}/api/list-trainers`, 'GET', 401],
      ['GET admin-data', `${ORIGIN}/api/admin-data?action=clubs`, 'GET', 401],
      ['POST push-record', `${ORIGIN}/api/push-record`, 'POST', 401],
      ['POST push-records', `${ORIGIN}/api/push-records`, 'POST', 401],
    ]

    for (const [name, url, method, expected] of apiChecks) {
      const r = await fetch(url, {
        method,
        headers: method === 'POST' ? { 'Content-Type': 'application/json' } : undefined,
        body: method === 'POST' ? '{}' : undefined,
      })
      check(r.status === expected, `${name} → ${r.status} (expected ${expected})`)
    }

    const html = await fetch(`${ORIGIN}/`).then((r) => r.text())
    const m = html.match(/\/assets\/(index-[^"]+\.js)/)
    check(Boolean(m), 'prod bundle hash in index.html')
    const cssM = html.match(/\/assets\/(index-[^"]+\.css)/)
    if (m) {
      const js = await fetch(`${ORIGIN}/assets/${m[1]}`).then((r) => r.text())
      check(js.includes('Выберите клуб'), 'prod bundle has current admin UI string')
      check(!js.includes('Все клубы'), 'prod bundle has no stale "Все клубы" string')
      check(js.includes('очередь отправлена') || js.includes('в очереди:'), 'prod sync feedback strings')
    }
    if (cssM) {
      const css = await fetch(`${ORIGIN}/assets/${cssM[1]}`).then((r) => r.text())
      check(css.includes('app-header__stopwatch'), 'prod bundle has header stopwatch styles')
    }

    if (!skipProdRoles) {
      run('prod roles API', 'node', ['scripts/qa-roles-prod.mjs', '--keep-users'])
      run('sales manager e2e', 'node', ['scripts/verify-sales-manager-e2e.mjs'])
      run('cleanup QA users', 'node', ['scripts/qa-roles-cleanup.mjs'])
    }
    run('prod features', 'node', ['scripts/verify-prod-features.mjs'])
  } catch (e) {
    console.error('✗ prod smoke:', e.message)
    failed++
  }
}

console.log('\n▶ static checks')
check(existsSync('dist/index.html'), 'dist/index.html exists')
check(existsSync('dist/sw.js'), 'dist/sw.js exists')

if (failed) {
  console.error(`\n${failed} check group(s) failed`)
  process.exit(1)
}
console.log('\nAll agent QA checks passed.')
