ALTER TABLE public.club_sales_plan
ADD COLUMN IF NOT EXISTS plan_nk NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (plan_nk >= 0),
ADD COLUMN IF NOT EXISTS plan_dk NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (plan_dk >= 0),
ADD COLUMN IF NOT EXISTS plan_uk NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (plan_uk >= 0);
